export const SQL_CHECK_USER: string = "select * from user_profile where user_id = ? limit 1";
export const SQL_INSERT_USER: string = "insert into user_profile(user_id, password) values (?,?)";
export const SQL_ALL_USER: string = "select * from user_profile";
export const SQL_UPDATE_USER: string = "update user_profile set user_id = ?, password= ? where u_id = ? limit 1 ";
export const SQL_DELETE_USER: string = "update user_profile set is_deleted = 1 where u_id = ? limit 1 ";
export const SQL_ADD_THEMES: string = "INSERT INTO themes (meta_data) VALUE (?)" ;
export const SQL_GET_THEMES: string = "SELECT * FROM themes";
export const SQL_UPDATE_THEME: string = "UPDATE theme SET meta_data = ? WHERE themes_id = ?";
export const SQL_DELETE_THEME: string = "Delete from themes where themes_id = ?";
export const SQL_SHOW_REELS : string = `select * from reels where is_deleted = 0 limit ? offset ?`;
export const SQL_SHOW_NEWS: string = `SELECT * from news where is_deleted = 0 limit ? offset ?`;